FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        iw \
        wireless-tools \
        network-manager \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ../wifi-scanner/scan_wifi.py /app/scan_wifi.py

ENV PYTHONUNBUFFERED=1
CMD ["python", "/app/scan_wifi.py"]
